---
abstract: 'Dive XML with XML::XPath and first-class collection + alpha'
author:
  - 'ytnobody <ytnobody@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.6.3, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-XPath-Diver
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  XML::XPath::Diver:
    file: lib/XML/XPath/Diver.pm
    version: 0.02
requires:
  Class::Builtin: 0
  XML::XPath: 0
  parent: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/ytnobody/XML-XPath-Diver/issues
  homepage: https://github.com/ytnobody/XML-XPath-Diver
  repository: git://github.com/ytnobody/XML-XPath-Diver.git
version: 0.02
